[colors.primary]
foreground = "#d5c4a1"
background = "#18120f"

[colors.normal]
black   = "#3c3836"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#d5c4a1"

[colors.bright]
black   = "#484442"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#fbf1c7"

[colors.footer_bar]
background = '#18120f'
foreground = '#ffdbca'

[colors.selection]
text       = "#362f2c"
background = "#ece0db"

[colors.cursor]
text   = "#974813"
cursor = "#ffb68f"

[colors.search.matches]
foreground = "#ffdbca"
background = "#773200"

[colors.search.focused_match]
foreground = "#974813"
background = "#ffdbca"

[colors.hints.start]
foreground = "#ffdbca"
background = "#5c4132"

[colors.hints.end]
foreground = "#ffdbca"
background = "#5c4132"
