[colors.primary]
foreground = "#d5c4a1"
background = "#282828"

[colors.normal]
black   = "#3c3836"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#d5c4a1"

[colors.bright]
black   = "#484442"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#fbf1c7"

[colors.footer_bar]
background = '#282828'
foreground = '#f6f6d5'

[colors.selection]
text       = "#282424"
background = "#e8e3e3"

[colors.cursor]
text   = "#9a9c30"
cursor = "#b8bb26"

[colors.search.matches]
foreground = "#f6f6d5"
background = "#444507"

[colors.search.focused_match]
foreground = "#9a9c30"
background = "#f6f6d5"

[colors.hints.start]
foreground = "#feefcd"
background = "#765300"

[colors.hints.end]
foreground = "#feefcd"
background = "#765300"
