[colors.primary]
foreground = "#d5c4a1"
background = "#121410"

[colors.normal]
black   = "#3c3836"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#d5c4a1"

[colors.bright]
black   = "#484442"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#fbf1c7"

[colors.footer_bar]
background = '#121410'
foreground = '#b3f39b'

[colors.selection]
text       = "#2f312d"
background = "#e2e3dc"

[colors.cursor]
text   = "#326b24"
cursor = "#98d782"

[colors.search.matches]
foreground = "#b3f39b"
background = "#19520c"

[colors.search.focused_match]
foreground = "#326b24"
background = "#b3f39b"

[colors.hints.start]
foreground = "#d7e8cc"
background = "#3d4b36"

[colors.hints.end]
foreground = "#d7e8cc"
background = "#3d4b36"
