legacy_layout=false

round_corners=10
background_alpha=0.4
background_color=000000

font_size=14
text_color=FFFFFF
position=top-left

table_columns=2
gpu_text=GPU
cpu_text=CPU

fps
fps_limit_method=late

fps_limit=144
fps_color_change
fps_color=B22222,FDFD09,39F900
fps_value=72,144

toggle_logging=Shift_L+F12
toggle_hud=Shift_L+F2

gamemode
