[screenshot]
last_region = "927,0,992,607"

[security_migrations]
calendar_credentials_v1 = true

[theme_templates]
applied_builtin_ids = "alacritty"

[wallpaper_panel]
flatten = true
sort = "date_desc"