services:
  user:
    - pipewire.service
    - pipewire.socket
    - pipewire-pulse.service
    - pipewire-pulse.socket
    - wireplumber.service
    - ydotool.service
    - gpg-agent.socket
    - gcr-ssh-agent.socket
  
  system:
    - thermald.service
    - power-profiles-daemon.service
    - earlyoom.service
    - bluetooth.service
    - docker.service
    - NetworkManager.service
    - warp-svc.service
    - libvirtd.service
    - virtlogd.service
