$lock_cmd = qs -c noctalia-shell ipc call lockScreen lock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 60 
    on-timeout = hyprctl dispatch dpms off || niri msg action power-off-monitors
    on-resume = hyprctl dispatch dpms on || niri msg action power-on-monitors
}

listener {
    timeout = 900
    on-timeout = $suspend_cmd
}
