#!/usr/bin/env sh
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$HYPRGAMEMODE" = 1 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword animation borderangle,0; \
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
	      keyword decoration:fullscreen_opacity 1;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
   
    brightnessctl -s set 100%
    qs -c noctalia-shell ipc call dock toggle
    qs -c noctalia-shell ipc call powerProfile set performance
else
  brightnessctl -r
  qs -c noctalia-shell ipc call dock toggle
  qs -c noctalia-shell ipc call powerProfile set powersaver
	hyprctl reload
fi
