monitor.alsa.rules = [
  {
    matches = [
      { api.alsa.card.name = "Audiocular Spark" }
    ]
    actions = {
      update-props = {
        audio.allowed-rates = [ 44100, 48000, 88200, 96000, 176400, 192000, 352800, 384000 ]
        session.suspend-timeout-seconds = 0
        priority.session = 1500
      }
    }
  }
]
