# gestures
gestures {
    workspace_swipe_distance = 300
    workspace_swipe_cancel_ratio = 0.2
    workspace_swipe_min_speed_to_force = 5
    workspace_swipe_direction_lock = true
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_create_new = true
}

gesture = 3, horizontal, workspace
gesture = 3, down, mod:CTRL, dispatcher, exec, pypr toggle sptlrx
gesture = 4, right, mod:ALT, dispatcher, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ 
gesture = 4, left, mod:ALT, dispatcher, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
gesture = 4, down, dispatcher, exec, grimblast copy area
gesture = 4, down, mod:ALT , dispatcher, exec, grim -g "$(slurp)" /tmp/g.png && curl -sF 'files[]=@/tmp/g.png' https://uguu.se/upload | jq -r '.files[0].url' | xargs -I{} xdg-open "https://lens.google.com/uploadbyurl?url={}"
gesture = 4, down, mod:SUPER ALT , dispatcher, exec, grim -g "$(slurp)" - | tesseract - - -l $(tesseract --list-langs | awk 'NR>1' | paste -sd+) | wl-copy

gesture = 4, pinchout, dispatcher, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.9) | if . < 1 then 1 else . end')
gesture = 4, pinchin, dispatcher, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.1')
