layerrule {
  name = waybar
  match:namespace = waybar
  ignore_alpha = 0.0
  animation = slide bottom
}

layerrule {
  name = gtk-layer-shell
  match:namespace = gtk-layer-shell
  blur = on
  ignore_alpha = 0.0
}

layerrule {
  name = sysvol
  match:namespace = syshud
  blur = on
  ignore_alpha = 0.0
}

layerrule {
  name = rofi
  match:namespace = rofi
  blur = on
  ignore_alpha = 0.0
  animation = slide down 80%
}

layerrule {
  name = swaync-control-center
  match:namespace = swaync-control-center
  blur = on
  ignore_alpha = 0.0
  animation = slide left
}

layerrule {
  name = swaync-notifications
  match:namespace = swaync-notification-window
  ignore_alpha = 0.0
  animation = slide down
}

layerrule {
  name = slurp
  match:namespace = selection|hyprpicker
  no_anim = on
}
