exec-once = systemctl --user start hyprpolkitagent 
exec-once = libinput-gestures
exec-once = waypaper --restore
exec-once = swaync 
exec-once = nm-applet
exec-once = blueman-applet
exec-once = waybar
exec-once = syshud 
exec-once = clipse -listen

# key binds
$mainMod = SUPER
bind = , Home, exec, normcap
bind = , Print, exec, flameshot gui
bind = ALT, M, exec, waypaper
bind = $mainMod, SPACE, exec, rofi -show drun -show-icons
bindr = SUPER, SUPER_L, exec, pkill -SIGUSR1 waybar

# recording
bindd = CTRL+Alt, R, Record region (no sound), exec, ~/.config/hypr/hyprland/scripts/record.sh # Record region (no sound)

# terminal opacity toggle
bind = ,F10, exec, ~/.config/hypr/scripts/kitty_opacity

# GameMode
#bind = , code:127, exec, ~/.config/hypr/scripts/gamemode 
bind = ALT, code:127, exec, ~/.config/hypr/scripts/monitor 
bind = ,code:117, exec, ~/.config/hypr/scripts/monitor

# brightness
binde = ,XF86MonBrightnessUp, exec, brightnessctl set +1%
binde = ,XF86MonBrightnessDown, exec, brightnessctl set 1%-

binde = ,code:74, exec, brightnessctl set +1%
binde = ,code:73, exec, brightnessctl set 1%-

# color pick
bind = CTRL, Q, exec, hyprpicker --autocopy --format=hex

# emoji
bind = $mainMod, E, exec, rofi -modi emoji -show emoji

# clipse
bind = SUPER, V, exec, ~/.config/hypr/scripts/clipse

# plugin keys
bind = SUPER, grave, overview:toggle

# laptop lid actions
bindl = , switch:Lid Switch,exec, hyprlock --immediate-render -q

# gestures
gesture = 4, right, dispatcher, exec, brightnessctl set +1%
gesture = 4, left, dispatcher, exec, brightnessctl set 1%-

gesture = 4, pinchout, dispatcher, exec, pypr zoom +1 
gesture = 4, pinchin, dispatcher, exec, pypr zoom -1
