$theme = adw-gtk3-dark
$icon = Fluent-teal-dark
$cursor = Bibata-Modern-Ice
$font = SauceCodePro Nerd Font Mono

$primary = rgb(cabeff)
$surface = rgb(141316)
$secondary = rgb(cac3dc)
$error = rgb(ffb4ab)
$tertiary = rgb(edb8cc)
$surface_lowest = rgb(0f0e11)
