$theme = adw-gtk3-dark
$icon = Fluent-teal-dark
$cursor = Bibata-Modern-Ice
$font = SauceCodePro Nerd Font Mono

$primary = rgb(ffb784)
$surface = rgb(18120f)
$secondary = rgb(e4bfa7)
$error = rgb(ffb4ab)
$tertiary = rgb(c8ca94)
$surface_lowest = rgb(120d0a)
