$theme = adw-gtk3-dark
$icon = Fluent-teal-dark
$cursor = Bibata-Modern-Ice
$font = SauceCodePro Nerd Font Mono

$primary = rgb(dbb8ff)
$surface = rgb(151218)
$secondary = rgb(d4bee8)
$error = rgb(ffb4ab)
$tertiary = rgb(ffb0ce)
$surface_lowest = rgb(100d13)
