ecosystem:enforce_permissions = true

permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/grim, screencopy, allow
permission = /usr/bin/wf-recorder, screencopy, allow
permission = /usr/bin/quickshell, screencopy, allow
permission = /usr/bin/hyprpicker, screencopy, allow
