# execute
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = qs -c noctalia-shell
exec-once = systemctl --user start hyprpolkitagent # remove on next qs release 

# binds
bindl= ,switch:on:Lid Switch, exec, loginctl lock-session

bindle = ,XF86MonBrightnessUp, exec, qs -c noctalia-shell ipc call brightness increase
bindle = ,XF86MonBrightnessDown, exec, qs -c noctalia-shell ipc call brightness decrease

bindle = ,code:74, exec, qs -c noctalia-shell ipc call brightness increase
bindle = ,code:73, exec, qs -c noctalia-shell ipc call brightness decrease

bind = SUPER, Space, exec,  qs -c noctalia-shell ipc call launcher toggle
bind = SUPER, grave, exec, qs -c noctalia-shell ipc call plugin:quickshell-overview toggle

bindr = SUPER, SUPER_L, exec, qs -c noctalia-shell ipc call bar toggle
bind = SUPER, E, exec, qs -c noctalia-shell ipc call launcher emoji
bind = Super, V, exec, qs -c noctalia-shell ipc call launcher clipboard
bind = alt, m,  exec,  qs -c noctalia-shell ipc call wallpaper toggle

bind = CTRL SHIFT, grave, exec, qs -c noctalia-shell ipc call notifications dismissAll
bind = SUPER, apostrophe,  exec, qs -c noctalia-shell ipc call notifications toggleHistory
bind = SUPER, semicolon,  exec, qs -c noctalia-shell ipc call controlCenter toggle
bind = SUPER, L,  exec, qs -c noctalia-shell ipc call calendar toggle

bindle = ,XF86MonBrightnessUp, exec, qs -c noctalia-shell ipc call brightness increase
bindle = ,XF86MonBrightnessDown, exec, qs -c noctalia-shell ipc call brightness decrease

bindle = ,code:74, exec, qs -c noctalia-shell ipc call brightness increase
bindle = ,code:73, exec, qs -c noctalia-shell ipc brightness decrease
bind = ALT, TAB, exec, qs -c noctalia-shell ipc call plugin:qs-hyprview toggle

# gestures
gesture = 4, right, dispatcher, exec, qs -c noctalia-shell ipc call brightness increase
gesture = 4, left, dispatcher, exec, qs -c noctalia-shell ipc call brightness decrease
gesture = 3, down, dispatcher, exec, qs -c noctalia-shell ipc call plugin:quickshell-overview open
gesture = 3, up, dispatcher, exec, qs -c noctalia-shell ipc call plugin:quickshell-overview close
gesture = 3, down, mod:ALT, dispatcher, exec, qs -c noctalia-shell ipc call plugin:qs-hyprview toggle


layerrule = dimaround, quickshell:plugin:qs-hyprview
