$NIpcCall = qs -c noctalia-shell ipc call

# autostart
exec-once = qs -c noctalia-shell

# brightness
bindle = , XF86MonBrightnessUp, exec, $NIpcCall brightness increase
bindle = , XF86MonBrightnessDown, exec, $NIpcCall brightness decrease
bindle = , CODE:74, exec, $NIpcCall brightness increase
bindle = , CODE:73, exec, $NIpcCall brightness decrease

# launchers / ui
bind = SUPER, SPACE, exec, $NIpcCall launcher toggle
bindr = SUPER, SUPER_L, exec, $NIpcCall bar toggle
bind = SUPER, E, exec, $NIpcCall launcher emoji
bind = SUPER, V, exec, $NIpcCall launcher clipboard
bind = ALT, M, exec, $NIpcCall wallpaper toggle

# notifications / panels
bind = CTRL SHIFT, GRAVE, exec, $NIpcCall notifications dismissAll
bind = SUPER, SEMICOLON, exec, $NIpcCall notifications toggleHistory
bind = SUPER, APOSTROPHE, exec, $NIpcCall controlCenter toggle
bind = SUPER, L, exec, $NIpcCall calendar toggle

# Recording 
bind = CTRL+ALT, R, exec, $NIpcCall screenRecorder toggle

# lock
bindl = , switch:on:Lid Switch, exec, loginctl lock-session

# plugins
bind = ALT, TAB, exec, $NIpcCall plugin:qs-hyprview toggle
bind = SUPER, GRAVE, exec, $NIpcCall plugin:quickshell-overview toggle

# gestures
gesture = 4, right, dispatcher, exec, $NIpcCall brightness increase
gesture = 4, left, dispatcher, exec, $NIpcCall brightness decrease
gesture = 3, down, dispatcher, exec, $NIpcCall plugin:quickshell-overview open
gesture = 3, up, dispatcher, exec, $NIpcCall plugin:quickshell-overview close
gesture = 3, down, mod:ALT, dispatcher, exec, $NIpcCall plugin:qs-hyprview toggle

# layer rule
layerrule {
  name = quickshell-hyprview
  match:namespace = quickshell:plugin:qs-hyprview
  dim_around = on
}

layerrule {
  name = quickshell-overview
  match:namespace = quickshell:overview
  animation = slide bottom 120%
}
