windowrule {
  name = float-all
  match:class = (.*)
  float = on
  center = on
}

windowrule {
  name = float-no-border
  match:float = true
  border_size = 0
}

windowrule {
  name = telegram
  match:initial_class = org.telegram.desktop
  no_screen_share = on
  size = 447 651
  move = 1466 47
}

windowrule {
  name = browser
  match:class = zen
  match:title = Zen Browser
  idle_inhibit = focus
  tile = on
  size = 752 882
  workspace = 1
}

windowrule {
  name = Pic-in-Pic
  match:title = Picture-in-Picture
  keep_aspect_ratio = on
  size = (monitor_w*0.30) (monitor_h*0.30)
  border_size = 0
  pin = on
}

windowrule {
  name = Calc
  match:title = org.gnome.Calculator
  size = 369 572
}

windowrule {
  name = terminal
  match:class = Alacritty
  tile = on
}

windowrule {
  name = burp-pro
  match:class = burp-StartBurp
  match:title = Burp Suite Professional v(.*) -(.*)- licensed to (.*)
  tile = on
  workspace = special
}

windowrule {
  name = burp-popups
  match:class = burp-StartBurp
  match:title = win.*
  center = false
}

windowrule {
  name = burp-search
  match:class = burp-StartBurp
  match:title = Burp Suite search
  size = 1713 989
}

windowrule {
  name = mpv
  match:class = mpv
  idle_inhibit = focus
  size = (monitor_w*0.35) (monitor_h*0.35)
  keep_aspect_ratio = on
  animation = popin 90%
}

windowrule {
  name = mpv-pin-float
  match:class = mpv
  pin = on
}

windowrule {
  name = spotify
  match:title = Spotify.*
  size = 800 950
}

windowrule {
  name = wine
  match:title = Wine configuration
  no_max_size = on
  size = 413 454
}

windowrule {
  name = bluemon-applet
  match:class = blueman-manager
  size = 552 682
  move = 1358 47
  animation = slide right
}

windowrule {
  name = wifi-editing
  match:class = nm-connection-editor
  match:title = Editing.*
  size = 666 602
}

windowrule {
  name = wifi-main
  match:class = nm-connection-editor
  size = 346 602
  move = 64 469
  animation = slide right
}

windowrule {
  name = Steam
  match:title = ^(SheepyAShortAdventure)$
  immediate = on
}

windowrule {
  name = qbittorrent
  match:class = org.qbittorrent.qBittorrent
  size = 962 785
}

windowrule {
  name = pavucontrol
  match:class = org.pulseaudio.pavucontrol
  size = 960 481
  move = 950 72
}

windowrule {
  name = discord
  match:class = vesktop
  size = 960 540
  workspace = 5
}

windowrule {
  name = obs
  match:class = com.obsproject.Studio
  size = 880 721
}

windowrule {
  name = waypaper
  match:class = waypaper
  size = 780 590
  move = 1130 480
}

windowrule {
  name = file-managers
  match:class = org.kde.dolphin
  size = 1235 716
  workspace = 2
}

windowrule {
  name = pdf-reader
  match:class = org.gnome.Evince
  size = 729 1013
}

windowrule {
  name = clipse
  match:title = tui-clipboard
  size = 622 652
}

windowrule {
  name = android-emulator
  match:title = .*Google Pixel 3 XL.*
  match:class = Genymotion Player
  size = 493 910
  move = 1396 134
}

windowrule {
  name = image-viewer
  match:class = viewnior
  size = 1403 848
}

windowrule {
  name = lutris
  match:class = net.lutris.Lutris
  size = 1115 633
}

windowrule {
  name = resources
  match:class = net.nokyan.Resources
  size = 788 896
}

windowrule {
  name = gimp
  match:title = GNU Image Manipulation Program
  match:class = gimp
  tile = on
}

windowrule {
  name = kdenlive
  match:title = Kdenlive
  match:class = org.kde.kdenlive
  tile = on
}

windowrule {
  name = virtmanager
  match:title = Virtual Machine Manager
  match:class = virt-manager
  tile = on
}

windowrule {
  name = Noctalia
  match:title = Noctalia
  match:class = org.quickshell
  size = 820 910
  pin = true
}

windowrule {
  name = idle-inhibit-fullscreen
  match:fullscreen = 1
  idle_inhibit = fullscreen
}
